// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOXqFWBZx-LONbHBA7qaIu2LxW1RW9M0g',
    appId: '1:343812380690:web:ed5cfdc0f4c9acf2cf20cb',
    messagingSenderId: '343812380690',
    projectId: 'chat-a3099',
    authDomain: 'chat-a3099.firebaseapp.com',
    storageBucket: 'chat-a3099.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-nUS7vlWNKz1J1LrcAbfYBfZTqabFOIU',
    appId: '1:343812380690:android:288ab0cf02b68d87cf20cb',
    messagingSenderId: '343812380690',
    projectId: 'chat-a3099',
    storageBucket: 'chat-a3099.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8FUiyomG5E6s6T9tN1GUCK3BqtqnZmPg',
    appId: '1:343812380690:ios:ae9cbb7fbff43604cf20cb',
    messagingSenderId: '343812380690',
    projectId: 'chat-a3099',
    storageBucket: 'chat-a3099.appspot.com',
    iosClientId: '343812380690-b9fsj05rljvdpd0pp378t4bscq4sot2d.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8FUiyomG5E6s6T9tN1GUCK3BqtqnZmPg',
    appId: '1:343812380690:ios:c95dc8bb49ce53b3cf20cb',
    messagingSenderId: '343812380690',
    projectId: 'chat-a3099',
    storageBucket: 'chat-a3099.appspot.com',
    iosClientId: '343812380690-vqqodfemqkp3jtvk152r0l9gepq5lfef.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
